### ISSUE TITLE
Hii!

### ISSUE THREAD

**Issue by parthu09** [jayskhatri/jayskhatri#1]
Hii,
My name is Parth and came to know about your profile when I joined the Github educational package. I am in grade 11 and I am very interested in app development, can you please advice how I should start my app development journey.
I loved your portfolio website and work!
Thanks and look forward to hearing from you!!

**Comment by jayskhatri** [comment]
Hey @parthu09 👋,

There are 2 options for you -
1. If you want to go with core android development or you can develop apps for android and iOS both. For cross platform apps, start learning flutter framework. You can find tutorials of Pawan Kumar on YouTube for free for flutter app development. 
2. If you want to go in core android development than start learning Kotlin/Java (recommended kotlin)

Let me know if you have any further doubt.
All the best.
